// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5QoZAY1-Y6K66C1XqL9LomrnMnUWnyqk',
    appId: '1:794990230464:web:7459a73ca83285fd97e625',
    messagingSenderId: '794990230464',
    projectId: 'flutter-quizz-a9ab4',
    authDomain: 'flutter-quizz-a9ab4.firebaseapp.com',
    databaseURL:
        'https://flutter-quizz-a9ab4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-quizz-a9ab4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyrFMXpHk8iIh-5udKZbmp2ouk1IqmxT8',
    appId: '1:794990230464:android:020daf5b40f0b5e597e625',
    messagingSenderId: '794990230464',
    projectId: 'flutter-quizz-a9ab4',
    databaseURL:
        'https://flutter-quizz-a9ab4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-quizz-a9ab4.appspot.com',
  );
}
